export const ADMIN_API_KEY = process.env.ADMIN_API_KEY;
export const USER_API_KEY = process.env.USER_API_KEY;
export const ELEVATOR_ACTIVATION_MICROCONTROLLER_API_KEY = process.env.ELEVATOR_ACTIVATION_MICROCONTROLLER_API_KEY